var apiResult = [ { latitude: -33.4194524,
    longitude: -70.6089823,
    timezone: 'America/Santiago',
    offset: -3,
    currently:
     { time: 1485729161,
       summary: 'Clear',
       icon: 'clear-day',
       precipIntensity: 0,
       precipProbability: 0,
       temperature: 70.91,
       apparentTemperature: 15.91,
       dewPoint: 57.96,
       humidity: 0.54,
       windSpeed: 5.13,
       windBearing: 249,
       visibility: 4.35,
       cloudCover: 0,
       pressure: 1011.83,
       ozone: 254.7 },
    hourly:
     { summary: 'Clear throughout the day.',
       icon: 'clear-day',
       data: [Object] },
    daily:
     { summary: 'Drizzle on Thursday, with temperatures peaking at 89°F on Wednesday.',
       icon: 'rain',
       data: [Object] },
    flags:
     { sources: [Object],
       'isd-stations': [Object],
       'madis-stations': [Object],
       units: 'us' } },
  { latitude: 47.3686,
    longitude: 8.5404,
    timezone: 'Europe/Zurich',
    offset: 1,
    currently:
     { time: 1485729165,
       summary: 'Clear',
       icon: 'clear-night',
       precipIntensity: 0,
       precipProbability: 0,
       temperature: 22.35,
       apparentTemperature: 18.34,
       dewPoint: 18.83,
       humidity: 0.86,
       windSpeed: 3.04,
       windBearing: 158,
       visibility: 6.21,
       cloudCover: 0.19,
       pressure: 1023.84,
       ozone: 271.22 },
    hourly:
     { summary: 'Light rain tomorrow morning and afternoon.',
       icon: 'rain',
       data: [Object] },
    daily:
     { summary: 'Light rain tomorrow through Sunday, with temperatures falling to 38°F tomorrow.',
       icon: 'rain',
       data: [Object] },
    flags:
     { sources: [Object],
       'isd-stations': [Object],
       'madis-stations': [Object],
       units: 'us' } },
  { latitude: -36.8535,
    longitude: 174.7656,
    timezone: 'Pacific/Auckland',
    offset: 13,
    currently:
     { time: 1485729165,
       summary: 'Partly Cloudy',
       icon: 'partly-cloudy-day',
       precipIntensity: 0,
       precipProbability: 0,
       temperature: 68.13,
       apparentTemperature: 68.13,
       dewPoint: 57.82,
       humidity: 0.7,
       windSpeed: 5.12,
       windBearing: 198,
       cloudCover: 0.31,
       pressure: 1021,
       ozone: 276.63 },
    hourly:
     { summary: 'Partly cloudy tomorrow morning.',
       icon: 'partly-cloudy-day',
       data: [Object] },
    daily:
     { summary: 'No precipitation throughout the week, with temperatures rising to 80°F on Sunday.',
       icon: 'clear-day',
       data: [Object] },
    flags:
     { sources: [Object],
       'isd-stations': [Object],
       'madis-stations': [Object],
       units: 'us' } },
  { latitude: -33.868,
    longitude: 151.21,
    timezone: 'Australia/Sydney',
    offset: 11,
    currently:
     { time: 1485729165,
       summary: 'Clear',
       icon: 'clear-day',
       precipIntensity: 0,
       precipProbability: 0,
       temperature: 80.36,
       apparentTemperature: 85.92,
       dewPoint: 75.56,
       humidity: 0.85,
       windSpeed: 3.74,
       windBearing: 9,
       visibility: 6.21,
       cloudCover: 0.09,
       pressure: 1012.4,
       ozone: 258.29 },
    hourly:
     { summary: 'Mostly cloudy starting this evening.',
       icon: 'partly-cloudy-night',
       data: [Object] },
    daily:
     { summary: 'Drizzle throughout the week, with temperatures bottoming out at 85°F on Wednesday.',
       icon: 'rain',
       data: [Object] },
    flags:
     { sources: [Object],
       'isd-stations': [Object],
       'madis-stations': [Object],
       units: 'us' } },
  { latitude: 51.5073,
    longitude: -0.1276,
    timezone: 'Europe/London',
    offset: 0,
    currently:
     { time: 1485729165,
       summary: 'Drizzle',
       icon: 'rain',
       nearestStormDistance: 0,
       precipIntensity: 0.0053,
       precipIntensityError: 0.0017,
       precipProbability: 0.5,
       precipType: 'rain',
       temperature: 46.97,
       apparentTemperature: 42.75,
       dewPoint: 45.98,
       humidity: 0.96,
       windSpeed: 8.77,
       windBearing: 215,
       visibility: 5.73,
       cloudCover: 0.89,
       pressure: 1006.1,
       ozone: 261.49 },
    hourly:
     { summary: 'Rain later tonight and tomorrow evening.',
       icon: 'rain',
       data: [Object] },
    daily:
     { summary: 'Light rain throughout the week, with temperatures peaking at 51°F on Thursday.',
       icon: 'rain',
       data: [Object] },
    flags:
     { sources: [Object],
       'darksky-stations': [Object],
       'datapoint-stations': [Object],
       'isd-stations': [Object],
       'madis-stations': [Object],
       units: 'us' } },
  { latitude: 41.681,
    longitude: 44.0287,
    timezone: 'Asia/Tbilisi',
    offset: 4,
    currently:
     { time: 1485729165,
       summary: 'Light Snow',
       icon: 'snow',
       precipIntensity: 0.0077,
       precipProbability: 0.39,
       precipType: 'snow',
       temperature: 7.47,
       apparentTemperature: 7.47,
       dewPoint: 5.99,
       humidity: 0.93,
       windSpeed: 1.15,
       windBearing: 317,
       cloudCover: 0.99,
       pressure: 1026.62,
       ozone: 400.23 },
    hourly:
     { summary: 'Light snow (1–2 in.) until tomorrow night.',
       icon: 'snow',
       data: [Object] },
    daily:
     { summary: 'Light snow (2–5 in.) today through Wednesday, with temperatures bottoming out at 21°F on Wednesday.',
       icon: 'snow',
       data: [Object] },
    flags: { sources: [Object], 'isd-stations': [Object], units: 'us' } } ]


export default apiResult